// ============================================
// TravelViet – Tour Data (shared across pages)
// ============================================
const TOURS_DATA = [
    {
        id: 1,
        title: 'Khám Phá Hạ Long Bay',
        dest: 'Quảng Ninh',
        category: 'cruise',
        price: 3500000,
        duration: 3,
        maxPeople: 20,
        spots: 15,
        emoji: '🚢',
        badge: 'HOT 🔥',
        rating: 5.0,
        reviews: 42,
        status: 'active',
        desc: 'Trải nghiệm vẻ đẹp huyền bí của Vịnh Hạ Long – một trong những kỳ quan thiên nhiên thế giới với hàng nghìn hòn đảo đá vôi kỳ vĩ nhô lên giữa làn nước xanh biếc. Tour bao gồm du thuyền cao cấp, hoạt động kayak khám phá hang động, thăm làng chài nổi trên biển và ẩm thực hải sản tươi ngon ngay trên vịnh.',
        schedule: [
            { day: 'Ngày 1', content: 'Hà Nội → Hạ Long – Lên tàu, check-in cabin, thăm hang Sửng Sốt' },
            { day: 'Ngày 2', content: 'Kayak khám phá hang Luồn, thăm làng chài Cửa Vạn, hoàng hôn trên vịnh' },
            { day: 'Ngày 3', content: 'Tập Tai Chi sáng sớm, thăm đảo Titop, trở về Hà Nội' },
        ],
        includes: ['Vé tàu khứ hồi Hà Nội – Hạ Long', 'Du thuyền 5 sao 2 đêm', 'Bữa ăn đầy đủ trên tàu', 'Hướng dẫn viên tiếng Việt/Anh', 'Kayak và thiết bị bơi lội', 'Bảo hiểm du lịch'],
        excludes: ['Chi phí cá nhân', 'Phí tham quan thêm', 'Đồ uống có cồn'],
        reviewList: [
            { name: 'Nguyễn Văn A', rating: 5, date: '15/03/2025', comment: 'Tour tuyệt vời! Hướng dẫn viên nhiệt tình, cảnh đẹp mê hồn. Du thuyền rất sang trọng và thoải mái. Chắc chắn sẽ quay lại lần sau!' },
            { name: 'Trần Thị B', rating: 5, date: '20/02/2025', comment: 'Vịnh Hạ Long đẹp hơn tôi tưởng rất nhiều. Kayak trong hang động là trải nghiệm đáng nhớ nhất. Đồ ăn trên tàu rất ngon!' },
            { name: 'Lê Minh C', rating: 4, date: '10/01/2025', comment: 'Cảnh đẹp không có gì để chê. Chỉ hơi đông khách một chút nhưng tổ chức tour rất chuyên nghiệp.' },
        ]
    },
    {
        id: 2,
        title: 'Phố Cổ Hội An Enchanting',
        dest: 'Quảng Nam',
        category: 'cultural',
        price: 1800000,
        duration: 2,
        maxPeople: 25,
        spots: 20,
        emoji: '🏮',
        badge: '',
        rating: 4.0,
        reviews: 28,
        status: 'active',
        desc: 'Đắm chìm vào không khí cổ kính của phố cổ Hội An với những ngôi nhà gỗ trăm năm tuổi, những chiếc đèn lồng lung linh nhiều màu sắc và ẩm thực đặc sắc. Khám phá những con phố nhỏ yên bình cùng với văn hóa giao thoa Việt – Nhật – Pháp độc đáo.',
        schedule: [
            { day: 'Ngày 1', content: 'TP.HCM → Đà Nẵng – Thăm phố cổ Hội An, chùa Cầu Nhật Bản' },
            { day: 'Ngày 2', content: 'Tham quan làng gốm Thanh Hà, may áo dài truyền thống, tắm biển Cửa Đại' },
        ],
        includes: ['Vé máy bay khứ hồi', 'Khách sạn 3 sao 1 đêm', 'Bữa ăn sáng và tối', 'Hướng dẫn viên'],
        excludes: ['Bữa trưa', 'Chi phí mua sắm', 'Vé tham quan riêng lẻ'],
        reviewList: [
            { name: 'Phạm Thị D', rating: 4, date: '05/03/2025', comment: 'Phố cổ Hội An rất đẹp và thơ mộng. Tour tổ chức tốt, chỉ hơi đông khách vào ban ngày.' },
            { name: 'Vũ Đình E', rating: 4, date: '18/02/2025', comment: 'Đèn lồng lung linh rất đẹp vào ban đêm. Đồ ăn Hội An tuyệt vời, đặc biệt là Cao Lầu và Mì Quảng!' },
        ]
    },
    {
        id: 3,
        title: 'Trekking Sapa Mây Bay',
        dest: 'Lào Cai',
        category: 'mountain',
        price: 4200000,
        duration: 4,
        maxPeople: 15,
        spots: 10,
        emoji: '⛰️',
        badge: 'NEW ⭐',
        rating: 4.8,
        reviews: 61,
        status: 'active',
        desc: 'Chinh phục những đỉnh núi hùng vĩ của Sapa, khám phá bản làng dân tộc thiểu số H\'Mông, Dao Đỏ và trải nghiệm những thửa ruộng bậc thang đẹp nhất Việt Nam trong làn sương mù huyền ảo.',
        schedule: [
            { day: 'Ngày 1', content: 'Hà Nội → Lào Cai (tàu đêm) – Sapa, thăm bản Cát Cát' },
            { day: 'Ngày 2', content: 'Trekking đến bản Sin Chải, ruộng bậc thang Mường Hoa' },
            { day: 'Ngày 3', content: 'Chinh phục Fansipan (cáp treo), ngắm hoàng hôn núi rừng' },
            { day: 'Ngày 4', content: 'Thăm chợ phiên Bắc Hà, trở về Hà Nội' },
        ],
        includes: ['Vé tàu khứ hồi Hà Nội – Lào Cai', 'Nhà nghỉ homestay 3 đêm', 'Bữa ăn đầy đủ', 'Hướng dẫn viên trekking', 'Vé cáp treo Fansipan'],
        excludes: ['Chi phí cá nhân', 'Đồ uống', 'Mua sắm tại chợ'],
        reviewList: [
            { name: 'Hoàng Anh F', rating: 5, date: '01/03/2025', comment: 'Trekking Sapa là trải nghiệm tuyệt vời nhất trong đời tôi! Phong cảnh hùng vĩ, người dân thân thiện.' },
            { name: 'Nguyễn Lan G', rating: 5, date: '14/02/2025', comment: 'Homestay rất ấm cúng và sạch sẽ. Đồ ăn dân tộc rất ngon. Hướng dẫn viên am hiểu văn hóa bản địa.' },
        ]
    },
    {
        id: 4,
        title: 'Đà Nẵng – Bà Nà Hills',
        dest: 'Đà Nẵng',
        category: 'city',
        price: 3200000,
        duration: 3,
        maxPeople: 30,
        spots: 25,
        emoji: '🌉',
        badge: '',
        rating: 5.0,
        reviews: 35,
        status: 'active',
        desc: 'Khám phá thành phố đáng sống nhất Việt Nam với Cầu Vàng nổi tiếng thế giới và trải nghiệm thế giới thần tiên tại Bà Nà Hills với kiến trúc Pháp cổ điển và vườn hoa tuyệt đẹp trên độ cao 1.400m.',
        schedule: [
            { day: 'Ngày 1', content: 'TP.HCM → Đà Nẵng – Thăm bán đảo Sơn Trà, chùa Linh Ứng' },
            { day: 'Ngày 2', content: 'Bà Nà Hills – Cầu Vàng, làng Pháp, vườn hoa Fantasy Park' },
            { day: 'Ngày 3', content: 'Phố cổ Hội An, tắm biển Mỹ Khê, về TP.HCM' },
        ],
        includes: ['Vé máy bay khứ hồi', 'Khách sạn 4 sao 2 đêm', 'Vé Bà Nà Hills', 'Xe đưa đón', 'Ăn sáng hàng ngày'],
        excludes: ['Bữa trưa và tối (tự túc)', 'Chi phí cá nhân'],
        reviewList: [
            { name: 'Trần Hùng H', rating: 5, date: '22/03/2025', comment: 'Cầu Vàng đẹp hơn trong ảnh rất nhiều! Bà Nà Hills cũng rất thú vị. Khách sạn sạch và đẹp. Recommend!' },
        ]
    },
    {
        id: 5,
        title: 'Phú Quốc Paradise Island',
        dest: 'Kiên Giang',
        category: 'beach',
        price: 6500000,
        duration: 5,
        maxPeople: 20,
        spots: 18,
        emoji: '🏝️',
        badge: 'HOT 🔥',
        rating: 5.0,
        reviews: 89,
        status: 'active',
        desc: 'Tận hưởng những bãi biển trong xanh tuyệt vời của đảo Phú Quốc – hòn đảo ngọc của Việt Nam với cát trắng mịn và nước biển màu ngọc bích. Tour bao gồm lặn biển ngắm san hô, thăm làng chài, trải nghiệm ẩm thực đặc sản biển.',
        schedule: [
            { day: 'Ngày 1', content: 'TP.HCM → Phú Quốc, nhận phòng resort 5 sao' },
            { day: 'Ngày 2', content: 'Tham quan Bắc Đảo: Vườn tiêu, Nhà tù Phú Quốc, chợ đêm' },
            { day: 'Ngày 3', content: 'Lặn biển ngắm san hô, câu cá, tiệc nướng hải sản trên thuyền' },
            { day: 'Ngày 4', content: 'Vinpearl Safari, vui chơi tự do tại bãi biển Kem' },
            { day: 'Ngày 5', content: 'Tự do buổi sáng, về TP.HCM chiều' },
        ],
        includes: ['Vé máy bay khứ hồi', 'Resort 5 sao 4 đêm', 'Ăn sáng hàng ngày', 'Tour lặn biển', 'Xe đưa đón sân bay'],
        excludes: ['Bữa trưa và tối', 'Chi phí tự phát sinh', 'Vé Vinpearl Safari'],
        reviewList: [
            { name: 'Mai Phương I', rating: 5, date: '10/03/2025', comment: 'Phú Quốc thiên đường thật sự! Biển trong xanh, đồ ăn ngon, dịch vụ 5 sao. Sẽ quay lại!' },
            { name: 'Đinh Long J', rating: 5, date: '28/02/2025', comment: 'Resort rất đẹp và thoải mái. Lặn biển ở đây cực kỳ tuyệt vời, san hô rất đa dạng và đẹp.' },
        ]
    },
    {
        id: 6,
        title: 'Mũi Né Cát Vàng',
        dest: 'Bình Thuận',
        category: 'beach',
        price: 2100000,
        duration: 2,
        maxPeople: 20,
        spots: 12,
        emoji: '🌊',
        badge: '',
        rating: 4.0,
        reviews: 17,
        status: 'active',
        desc: 'Khám phá đồi cát vàng và cát đỏ huyền bí, trải nghiệm lướt ván diều trên biển xanh ngắt. Mũi Né nổi tiếng với những cồn cát trải dài bất tận và làng chài cổ kính yên bình.',
        schedule: [
            { day: 'Ngày 1', content: 'TP.HCM → Mũi Né, thăm đồi cát vàng, trượt cát, hoàng hôn trên biển' },
            { day: 'Ngày 2', content: 'Đồi cát đỏ bình minh, làng chài Mũi Né, suối Tiên, về TP.HCM' },
        ],
        includes: ['Xe khách khứ hồi', 'Khách sạn 3 sao 1 đêm', 'Ăn sáng', 'Hướng dẫn viên'],
        excludes: ['Phí thuê xe ATV', 'Bữa trưa và tối', 'Chi phí vui chơi thêm'],
        reviewList: [
            { name: 'Bùi Trang K', rating: 4, date: '03/03/2025', comment: 'Đồi cát Mũi Né rất đẹp, trải nghiệm ATV thú vị. Hơi nóng nhưng xứng đáng!' },
        ]
    },
    {
        id: 7,
        title: 'Ninh Bình – Tràng An',
        dest: 'Ninh Bình',
        category: 'cultural',
        price: 1600000,
        duration: 2,
        maxPeople: 25,
        spots: 20,
        emoji: '⛩️',
        badge: '',
        rating: 4.2,
        reviews: 23,
        status: 'active',
        desc: 'Khám phá Tràng An – Di sản thiên nhiên và văn hóa thế giới với những hang động kỳ bí và đền chùa cổ kính ẩn giữa núi non hùng vĩ. Tham quan Cố đô Hoa Lư, chèo thuyền trên sông Ngô Đồng.',
        schedule: [
            { day: 'Ngày 1', content: 'Hà Nội → Ninh Bình, thăm cố đô Hoa Lư, hang Múa lúc hoàng hôn' },
            { day: 'Ngày 2', content: 'Chèo thuyền Tràng An, thăm Bích Động, chùa Bái Đính, về Hà Nội' },
        ],
        includes: ['Xe khách khứ hồi', 'Khách sạn 3 sao 1 đêm', 'Ăn sáng', 'Vé thuyền Tràng An', 'Vé Bái Đính'],
        excludes: ['Bữa trưa và tối', 'Chi phí cá nhân'],
        reviewList: [
            { name: 'Cao Sơn L', rating: 4, date: '12/02/2025', comment: 'Tràng An đẹp như tranh vẽ! Chèo thuyền qua hang động rất ấn tượng. Tour tổ chức gọn gàng.' },
        ]
    },
    {
        id: 8,
        title: 'Côn Đảo Hoang Sơ',
        dest: 'Bà Rịa – Vũng Tàu',
        category: 'beach',
        price: 7200000,
        duration: 4,
        maxPeople: 12,
        spots: 8,
        emoji: '🌺',
        badge: 'VIP ⭐',
        rating: 5.0,
        reviews: 11,
        status: 'active',
        desc: 'Trải nghiệm thiên nhiên hoang sơ của Côn Đảo với những bãi biển đẹp nhất Việt Nam, lặn biển ngắm san hô và khám phá lịch sử hào hùng của dân tộc tại hệ thống nhà tù Côn Đảo.',
        schedule: [
            { day: 'Ngày 1', content: 'TP.HCM → Côn Đảo, nhận phòng, tham quan thị trấn' },
            { day: 'Ngày 2', content: 'Lặn biển ngắm san hô, bãi Đầm Trầu, hoàng hôn' },
            { day: 'Ngày 3', content: 'Vườn quốc gia, quan sát rùa biển, đảo nhỏ' },
            { day: 'Ngày 4', content: 'Khu di tích nhà tù, nghĩa trang Hàng Dương, về TP.HCM' },
        ],
        includes: ['Vé máy bay khứ hồi', 'Resort 4 sao 3 đêm', 'Bữa ăn đầy đủ', 'Tour lặn biển', 'Hướng dẫn viên lịch sử'],
        excludes: ['Chi phí cá nhân', 'Mua sắm'],
        reviewList: [
            { name: 'Dương Hải M', rating: 5, date: '25/02/2025', comment: 'Côn Đảo là điểm đến tuyệt vời nhất tôi từng đến. Biển đẹp, không khí trong lành, lịch sử sâu sắc.' },
        ]
    },
];
